name:                lmchat-tui
version:             0.1.0.0
github:              "githubuser/lmchat-tui"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lmchat-tui#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- containers
- text
- bytestring
- aeson
- mtl
- aeson
- lens
- lens-aeson
- brick
- vty
- vty-crossplatform
- network
- http-client
- http-client-tls
- http-types
- process
- insc
- filepath
- Glob
- vector
- temporary

default-extensions:
- FlexibleInstances
- FlexibleContexts
- UndecidableInstances
- OverloadedRecordDot
- DuplicateRecordFields
- ScopedTypeVariables
- TupleSections
- DeriveGeneric
- QuasiQuotes
- DeriveDataTypeable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lmchat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lmchat-tui
    - cmdargs
    - natural-sort
    - directory
    - lens-aeson
    - yaml

tests:
  lmchat-tui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lmchat-tui
