name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2.7.3
      with:
        enable-stack: true
        ghc-version: '9.6.5'
        cabal-version: '3.10'
        stack-version: '2.15'

    - name: Cache dependencies on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      uses: actions/cache@v4
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('stack.yaml') }}-${{ matrix.cache-bust }}
    - name: Cache dependencies on Windows
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
          C:\sr
        key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('stack.yaml') }}-${{ matrix.cache-bust }}

    - name: Build
      run: |
        stack config set system-ghc --global true
        stack install --local-bin-path ./dist

    - name: Compress package on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      run: |
        tar -czvf \
          $(echo lmchat-${{ runner.os }}-${{ runner.arch }} | tr '[:upper:]' '[:lower:]')-bin.tar.gz \
          -C dist lmchat
    - name: Compress package on Windows
      if: startsWith(runner.os, 'Windows')
      run: |
        Compress-Archive -Path dist/lmchat.exe -DestinationPath "lmchat-windows-${{ runner.arch }}-bin.zip".toLower()

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lmchat-bin-${{ runner.os }}-${{ runner.arch }}
        path: |
          lmchat-*.tar.gz
          lmchat-*.zip

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: lmchat-bin-*
          path: dist
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: skiars/lmchat-tui
          files: dist/*
          draft: true
          overwrite: true
